name: ci backend
on: [push, pull_request]

defaults:
  run:
    working-directory: database-service

jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-lastest]
        node-version: [12.x] 

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm ci
    - name: run unit test
      run: | 
        npm run-script build

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-lastest,macos-latest]
        node-version: [12.x] 

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm ci
    - name: run unit test
      run: | 
        npm run test
    - name: run e2e test
      run : |
        npm run test:e2e
